images_path: "images"
temp_directory: "temp" # temp_directory will be placed relative to images_path
http_server_port: 8000
chromecast_name: "Basement Lights TV"
slideshow_duration_seconds: 15
max_image_height_pixels: 720